name: Terraform Azure Deployment

on:
  push:
    branches:
    - master

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -out=tfplan \
        -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
        -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
        -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
        -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
        -var="admin_password=${{ secrets.ARM_ADMIN_PASSWORD }}" \

        ls -lla
        pwd


    # - name: Terraform Apply
#   run: terraform apply -auto-approve tfplan
